# Generated by Django 4.2.7 on 2023-12-01 11:28

import Task.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Your title should contain words, numbers and _ and start with words.', max_length=150, unique=True, validators=[Task.validators.check_text])),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
